### ISSUE TITLE
toc does not display first-level headings

### ISSUE THREAD

**Issue by levinit** [Fentaniao/Liquid#16]
example:
```markdown
[toc]

# level 1
## level 2
```

"level 1 "  deos not display in TOC.

**Comment by levinit** [comment]
![图片](https://user-images.githubusercontent.com/24387319/195266315-db0d6475-481a-4fef-95c2-e87071bfe312.png)

markdown
![图片](https://user-images.githubusercontent.com/24387319/195266341-94433634-458b-4d32-b1f8-8560732f3936.png)

**Comment by ruiyangzhou01** [comment]
Thank you for your issue and sorry to answer you so late.

## Reason

In the last Release v0.4.0, line 353 - 355 of [main.css,](https://github.com/Fentaniao/Liquid/blob/v0.4.0/src/liquid/main.css) I code as follows,

``` css
.md-toc-h1 {
    display: none;
}
```

## Why I design Liquid like this

I consider this as a feasture of Liquid, because I suppose that people usually use TOC in the condition as follows

``` markdown
# The titile of the file

[toc]

## Section

## Subsection

## Section

## Subsection
```

In this markdown article of other theme, it will display the h1 title twice. Due to h1 in the article and in  the TOC are so big, that means that it will use a lot of space to display it repeatedly.

## An imporvement maybe included in the future release

What you mention is also a usual usage which people use h1 many times to start a new chapter.

I consider to make a custom css, in which it can provide people some common options to custom Liquid. This imporvement will be release soon.

If you have any advise, please share with me. I will appreaciate it for you.

**Comment by levinit** [comment]
thx your reply, yes, I use h1 as a chapter title ,🤔

**Comment by ruiyangzhou01** [comment]
The new release will take this scenario into consideration. Before I release the new version, you can delete or comment this code in CSS
```
.md-toc-h1 {
    display: none;
}
```
